# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updatetime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problems', models.CharField(max_length=1024)),
                ('method', models.CharField(max_length=2048)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updatetime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoringRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.CharField(max_length=2048)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updatetime', models.DateField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updatetime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='ps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProblemSet'),
        ),
    ]
