# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scoringrecord',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scoringrecord',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
